//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangDingJiLu
    {
        public long AutoID { get; set; }
        public string cChePaiHao { get; set; }
        public string openid { get; set; }
        public Nullable<System.DateTime> dShiJian { get; set; }
        public Nullable<int> iBangDingLeiXing { get; set; }
        public string cCreate { get; set; }
        public Nullable<int> iDelete { get; set; }
        public Nullable<int> iFangShi { get; set; }
    }
}
