//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoXianJiLu
    {
        public long AutoID { get; set; }
        public string cChePaiHao { get; set; }
        public string cBaoXianGongShi { get; set; }
        public string cXianZhong { get; set; }
        public string cBaoXianHao { get; set; }
        public Nullable<decimal> iBaoE { get; set; }
        public Nullable<System.DateTime> dTouBaoRiQi { get; set; }
        public Nullable<System.DateTime> dDaoQiRiQi { get; set; }
        public string cBeiZhu { get; set; }
    }
}
