//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class CangKuInfo
    {
        public string cCangKuBianMa { get; set; }
        public string cCangKuMingCheng { get; set; }
        public string cDiZhi { get; set; }
        public string cLianXiRen { get; set; }
        public string cLianXiDianHua { get; set; }
        public string cZuoJi { get; set; }
        public string cBeiZhu { get; set; }
    }
}
