//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheLiangInfo
    {
        public long AutoID { get; set; }
        public string cChePaiHao { get; set; }
        public string cPinPai { get; set; }
        public string cXingHao { get; set; }
        public string cCheJiaHao { get; set; }
        public string cFaDongJiHao { get; set; }
        public Nullable<System.DateTime> dGouMaiRiQi { get; set; }
        public Nullable<System.DateTime> dNianShenRiQi { get; set; }
        public Nullable<decimal> iTuFangShu { get; set; }
        public string cCheLiangSuoShu { get; set; }
        public string cXZDWBianMa { get; set; }
        public string openid { get; set; }
        public string cCheLiangLeiBie { get; set; }
        public Nullable<bool> bShiFouBaoFei { get; set; }
        public Nullable<System.DateTime> dBaoFeiRiQi { get; set; }
        public string cBeiZhu { get; set; }
    }
}
