//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class GongChengCheDingDan
    {
        public long AutoID { get; set; }
        public string cGongDiBianMa { get; set; }
        public Nullable<System.DateTime> dDanJuRiQi { get; set; }
        public string cChePaiHao { get; set; }
        public string openid { get; set; }
        public Nullable<System.DateTime> dQiYunShiJian { get; set; }
        public string cXianLuBianMa { get; set; }
        public string cXZDWBianMa { get; set; }
        public Nullable<System.DateTime> dQueRenShiJian { get; set; }
        public string cGuanLiYuanBianMa { get; set; }
        public Nullable<int> iState { get; set; }
        public string cState { get; set; }
        public Nullable<int> iTWState { get; set; }
        public string cTWState { get; set; }
        public string cBeiZhu { get; set; }
    }
}
