//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class GongDiInfo
    {
        public string cGongDiBianMa { get; set; }
        public string cGongDiMingCheng { get; set; }
        public string cYeZhuBianMa { get; set; }
        public string cYeZhuMingCheng { get; set; }
        public Nullable<decimal> iTuFangShu { get; set; }
        public Nullable<decimal> iDanJia { get; set; }
        public Nullable<decimal> iZongJia { get; set; }
        public string cCeHuiRen { get; set; }
        public string cFuZeRen { get; set; }
        public string cLianXiRen { get; set; }
        public string cLianXiDianHua { get; set; }
        public string cHeTongBianMa { get; set; }
        public string cHeTongMingCheng { get; set; }
        public Nullable<System.DateTime> dQianDingRiQi { get; set; }
        public string cHeTongNeiRong { get; set; }
        public string cChengFaNeiRong { get; set; }
        public Nullable<System.DateTime> dTingYongRiQi { get; set; }
        public string cDiZhi { get; set; }
        public string cBeiZhu { get; set; }
        public string cCreate { get; set; }
        public Nullable<System.DateTime> dCreate { get; set; }
    }
}
