//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class JiaYouJiLu
    {
        public long AutoID { get; set; }
        public string cChePaiHao { get; set; }
        public Nullable<System.DateTime> dJiaYouJiLu { get; set; }
        public string cJiaYouKaHao { get; set; }
        public string cJiaYouLeiXing { get; set; }
        public Nullable<decimal> iYouLiang { get; set; }
        public Nullable<decimal> iDanJia { get; set; }
        public Nullable<decimal> iJinE { get; set; }
        public Nullable<decimal> iDanQiangLiCheng { get; set; }
        public string cBeiZhu { get; set; }
    }
}
