//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShangPinChuKu
    {
        public System.Guid gCKID { get; set; }
        public string cChuKuBianMa { get; set; }
        public Nullable<System.DateTime> dChuKuRiQi { get; set; }
        public string cCangKuBianMa { get; set; }
        public Nullable<int> iChuKuLeiBie { get; set; }
        public string cChuKuLeiBie { get; set; }
        public string cBeiZhu { get; set; }
        public Nullable<int> iState { get; set; }
        public string cState { get; set; }
        public string cCreate { get; set; }
        public Nullable<System.DateTime> dCreate { get; set; }
        public string cModify { get; set; }
        public Nullable<System.DateTime> dModify { get; set; }
        public string cAuditor { get; set; }
        public Nullable<System.DateTime> dAuditor { get; set; }
    }
}
