//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShangPinInfo
    {
        public long AutoID { get; set; }
        public string cDaLeiBianMa { get; set; }
        public string cShangPinBianMa { get; set; }
        public string cShangPinMingCheng { get; set; }
        public string cGuiGeXingHao { get; set; }
        public string cJiLiangDanWei { get; set; }
        public Nullable<decimal> iAnQuanKuCun { get; set; }
        public string cBeiZhu { get; set; }
    }
}
