//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiGuJiLu
    {
        public long AutoID { get; set; }
        public string cChePaiHao { get; set; }
        public Nullable<System.DateTime> dShiGuRiQi { get; set; }
        public string cZeRenGuiShu { get; set; }
        public string cFaShengDiDian { get; set; }
        public string openid { get; set; }
        public string cDuiFangChePai { get; set; }
        public string cDuiFangJiaShiYuan { get; set; }
        public string cDuiFangDianHua { get; set; }
        public Nullable<decimal> iPeiFuDuiFangJinE { get; set; }
        public Nullable<decimal> iDuiFangPeiFuJinE { get; set; }
        public Nullable<decimal> iGongShiChengDanJinE { get; set; }
        public Nullable<decimal> iGeRenChengDanJinE { get; set; }
        public Nullable<System.DateTime> dChuLiRiQi { get; set; }
        public string cChuLiQingKuan { get; set; }
        public Nullable<bool> bShiFouChuXian { get; set; }
        public string cBeiZhu { get; set; }
    }
}
