//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreRecord
    {
        public long AutoID { get; set; }
        public Nullable<int> iFlag { get; set; }
        public Nullable<System.Guid> gID { get; set; }
        public string cDanJuMingCheng { get; set; }
        public string cDanJuHao { get; set; }
        public Nullable<System.DateTime> dRiQi { get; set; }
        public Nullable<long> iID { get; set; }
        public string cShangPinBianMa { get; set; }
        public Nullable<decimal> iShuLiang { get; set; }
        public Nullable<decimal> iDanJia { get; set; }
        public Nullable<decimal> iJinE { get; set; }
    }
}
