//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_User
    {
        public string cUserCode { get; set; }
        public string cUserName { get; set; }
        public string cPassword { get; set; }
        public string cGroupCode { get; set; }
        public Nullable<bool> bSelf { get; set; }
        public Nullable<bool> bIsAdmin { get; set; }
        public Nullable<bool> bGroup { get; set; }
        public Nullable<bool> bIsStop { get; set; }
    }
}
