//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_AbleHold
    {
        public string cAbleCode { get; set; }
        public string cAbleName { get; set; }
        public string cUserCode { get; set; }
        public Nullable<bool> bEdit { get; set; }
        public Nullable<bool> bPrint { get; set; }
        public Nullable<bool> bAudit { get; set; }
        public Nullable<bool> bUnAudit { get; set; }
        public Nullable<bool> bExport { get; set; }
    }
}
