//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaJueJiDingDan
    {
        public long AutoID { get; set; }
        public string cDingDanHao { get; set; }
        public string cGongDiBianMa { get; set; }
        public Nullable<System.DateTime> dDanJuRiQi { get; set; }
        public string cChePaiHao { get; set; }
        public string openid { get; set; }
        public string cShangBanBianMa { get; set; }
        public Nullable<System.DateTime> dKaiShiShiJian { get; set; }
        public Nullable<System.DateTime> dJieShuShiJian { get; set; }
        public Nullable<decimal> iXiaoShiShu { get; set; }
        public Nullable<System.DateTime> dQueRenShiJian { get; set; }
        public string cGuanLiYuanBianMa { get; set; }
        public Nullable<int> iState { get; set; }
        public string cState { get; set; }
        public string cBeiZhu { get; set; }
        public Nullable<int> iBiaoShi { get; set; }
        public string cCreate { get; set; }
        public Nullable<bool> bPrint { get; set; }
    }
}
