//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class wechatUser
    {
        public string openid { get; set; }
        public string nickname { get; set; }
        public Nullable<int> sex { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string headimgurl { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> audit { get; set; }
        public string auditdes { get; set; }
        public string role_code { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public string cXingMing { get; set; }
        public string cShenFenZhengHao { get; set; }
        public string cZhunJiaCheXing { get; set; }
        public Nullable<System.DateTime> dRuZhiRiQi { get; set; }
        public string cHuJi { get; set; }
        public string cLianXiDianHua { get; set; }
        public string cJinJiLianXiRen { get; set; }
        public string cJinJiLianXiRenGuanXi { get; set; }
        public string cJinJiLianXiDianHua { get; set; }
        public string cJiaShiYuanShuXing { get; set; }
        public Nullable<bool> bStop { get; set; }
        public Nullable<System.DateTime> dStop { get; set; }
        public string cBeiZhu { get; set; }
    }
}
