//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeiZhangJiLu
    {
        public long AutoID { get; set; }
        public string cChePaiHao { get; set; }
        public Nullable<System.DateTime> dWeiZhangRiQi { get; set; }
        public string cWeiZhangLeiXing { get; set; }
        public string cWeiZhangDiZhi { get; set; }
        public string cWeiZhangMiaoShu { get; set; }
        public string openid { get; set; }
        public Nullable<decimal> iFaKuanJinE { get; set; }
        public Nullable<decimal> iZiFuJinE { get; set; }
        public Nullable<System.DateTime> dChuLiRiQi { get; set; }
        public string cBeiZhu { get; set; }
        public Nullable<int> iState { get; set; }
        public string cState { get; set; }
        public string cCreate { get; set; }
        public Nullable<System.DateTime> dCreate { get; set; }
        public string cModify { get; set; }
        public Nullable<System.DateTime> dModify { get; set; }
        public string cAuditor { get; set; }
        public Nullable<System.DateTime> dAuditor { get; set; }
    }
}
