//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class XianLuInfo
    {
        public int AutoID { get; set; }
        public string cXianLuBianMa { get; set; }
        public string cGongDiBianMa { get; set; }
        public string cGongDiMingCheng { get; set; }
        public string cTuWeiBianMa { get; set; }
        public string cTuWeiMingCheng { get; set; }
        public Nullable<decimal> iGongLiShu { get; set; }
        public Nullable<decimal> iJinE { get; set; }
        public Nullable<int> iShiJian { get; set; }
        public string cBeiZhu { get; set; }
        public string cCreate { get; set; }
        public Nullable<System.DateTime> dCreate { get; set; }
        public Nullable<int> iState { get; set; }
        public string cState { get; set; }
        public Nullable<bool> bStop { get; set; }
        public Nullable<System.DateTime> dStop { get; set; }
        public Nullable<decimal> iWaiBuJinE { get; set; }
    }
}
