//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class XieZuoDanWeiDaLei
    {
        public string cDaLeiBianMa { get; set; }
        public string cDaLeiMingCheng { get; set; }
        public Nullable<int> iJiCi { get; set; }
        public Nullable<bool> bEnd { get; set; }
    }
}
