//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class YeZhuInfo
    {
        public string cYeZhuBianMa { get; set; }
        public string cQiYeMingCheng { get; set; }
        public string cZhuCeDiZhi { get; set; }
        public string cBanGongDiZhi { get; set; }
        public string cZhuCeHao { get; set; }
        public string cFaRen { get; set; }
        public string cLianXiRen1 { get; set; }
        public string cShouJiHao1 { get; set; }
        public string cLianXiRen2 { get; set; }
        public string cShouJiHao2 { get; set; }
        public string cZuoJi { get; set; }
        public string cKaiHuMingCheng { get; set; }
        public string cKaiHuHang { get; set; }
        public string cYinHangZhangHao { get; set; }
        public string cBeiZhu { get; set; }
    }
}
