//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class YeZhuHuiYiJiLu
    {
        public long AutoID { get; set; }
        public string cYeZhuBianMa { get; set; }
        public Nullable<System.DateTime> dKaiHuiRiQi { get; set; }
        public string cHuiYiYiTi { get; set; }
        public string cKaiHuiDiDian { get; set; }
        public string cCanHuiRenYuan { get; set; }
        public string cHuiYiNeiRong { get; set; }
        public string cBeiZhu { get; set; }
    }
}
